"""create events table

Revision ID: c6b89758defb
Revises: 
Create Date: 2025-12-18 23:29:54.274528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b89758defb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.String(length=255), nullable=False),
    sa.Column('event_start_date', sa.DateTime(), nullable=False),
    sa.Column('event_end_date', sa.DateTime(), nullable=False),
    sa.Column('event_registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('HACKATHON', 'MEETUP', 'WORKSHOP', name='event_type_name'), nullable=False),
    sa.Column('event_assignees', sa.JSON(), nullable=True),
    sa.Column('event_organization', sa.String(length=255), nullable=False),
    sa.Column('event_status', sa.Enum('OFFLINE', 'ONLINE', 'HYBRID', name='event_status_name'), nullable=False),
    sa.Column('event_location', sa.String(length=255), nullable=True),
    sa.Column('event_themes', sa.JSON(), nullable=True),
    sa.Column('event_rules', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_start_date'), ['event_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_status'), ['event_status'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventID', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['eventID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eventID')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_event_status'))
        batch_op.drop_index(batch_op.f('ix_events_event_start_date'))
        batch_op.drop_index(batch_op.f('ix_events_event_name'))

    op.drop_table('events')
    # ### end Alembic commands ###
